### ISSUE TITLE
Feedback about Microsoft Lean 

### ISSUE THREAD

**Issue by GhostMelodie** [MicrosoftDocs/Contribute.fr-FR#4]
Hello  
  
I am writing a few words to let you know that I particularly appreciate Microsoft Learn, for me it is a good revision of the concepts already acquired and some times acquiring new knowledge.  But...  
  
I have to admit that the questions sections are often full of errors, nonsense, and useless verbiage, which for me taints the like and useful side of Microsoft Learn.  Sorry to let you know...  
  
Thank you. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Guide du contributeur Microsoft Docs - Vue d’ensemble - Contributor Guide](https://docs.microsoft.com/fr-fr/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.fr-fr/blob/live/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by GhostMelodie** [comment]
Bonjour 
 
Je vous écris c’est quelques mots pour vous faire savoir que j’apprécie particulièrement Microsoft Learn, pour moi c’est une bonne révision des concepts déjà acquit et certaine fois l’acquisition de nouvelle connaissance.  Mais... 
 
Je dois admettre que les sections questions sont souvent pleines erreurs, de non-sens, et de verbiage sans utilité, ce qui pour moi entache le coté plaisent et utiles de Microsoft Learn.  Désolé de vous le faire savoir... 
 
Merci.

**Comment by GhostMelodie** [comment]
After reading the comment you can close the ticket. 
Après avoir pris connaissance du commentaire vous pourrez fermer le ticket. 
 
Merci / Thank you

**Comment by srvbpigh** [comment]
Hello, @GhostMelodie
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @GhostMelodie 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by GhostMelodie** [comment]
I already send correction for one bad question/response. I rapidly find other errors after that.  Try to update quality department. I can't invest more time on this. 

Regards,

**Comment by V-vafune** [comment]
Hello, @GhostMelodie , 

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @GhostMelodie ,

Thanks once again for your comment.

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
